version: '3.8'
services:
  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=GMT+5

  server:
    build: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      TZ: 'GMT+5'

  db:
    image: postgres:13.7-alpine
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: 'GMT+5'


