DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS public.users (
	user_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NULL UNIQUE,
	name varchar(255) NULL,
	CONSTRAINT PK_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.items (
	item_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	available bool NULL,
	description varchar(255) NULL,
	name varchar(255) NULL,
	user_id int8 NULL,
    CONSTRAINT PK_items PRIMARY KEY (item_id),
	CONSTRAINT FK_items FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.comments (
	comment_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created timestamp NULL,
	text varchar(255) NULL,
	item_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT PK_comments PRIMARY KEY (comment_id),
	CONSTRAINT FK1_comments_item_id FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE ON UPDATE RESTRICT,
	CONSTRAINT FK2_comments_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE public.bookings (
	booking_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	end_time timestamp NULL,
	start_time timestamp NULL,
	status varchar(255) NULL,
	item_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT PK_bookings PRIMARY KEY (booking_id),
	CONSTRAINT FK1_bookings_item_id FOREIGN KEY (item_id) REFERENCES public.items(item_id) ON DELETE CASCADE ON UPDATE RESTRICT,
	CONSTRAINT FK2_bookings_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE ON UPDATE RESTRICT
);
